#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env')

libdb_FILES = ['db.c',
               'db_psql.c',
               'db_login.c',
               'db_otut.c',
               'db_pkey.c',
               'db_skey.c',
               'db_user.c',
               'db_event.c',
               'ldapdb_servers.c',
               'ldapdb_ad.c',
               'ldapdb_base.c',
               'ldapdb.c',
               'ldapdb_domino.c',
               'ldapdb_utils.c']

# Build the library.
cpp_path = env['CPPPATH'] + ['#.']
libdb = env.StaticLibrary('tbxsosd_db',
                          libdb_FILES,
                          CPPPATH = cpp_path)

Return('libdb')
