#
# Copyright (C) 2006-2012 Opersys inc.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License, notany later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('env')

libdb_FILES = ['db.c',
               'db_psql.c',
               'db_login.c',
               'db_otut.c',
               'db_pkey.c',
               'db_skey.c',
               'db_user.c',
               'db_event.c',
               'ldapdb_servers.c',
               'ldapdb_ad.c',
               'ldapdb_base.c',
               'ldapdb.c',
               'ldapdb_domino.c',
               'ldapdb_utils.c']

# Build the library.
cpp_path = env['CPPPATH'] + ['#libutils', '#common']
libdb = env.StaticLibrary('tbxsosd_db',
                          libdb_FILES,
                          CPPPATH = cpp_path)

Return('libdb')
