#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
Import('env conf_options')

def template_build(target, source, env):
    for a_target, a_source in zip(target, source):
        targetFile = file(str(a_target), "w")
        sourceFile = file(str(a_source), "r")
        targetFile.write(sourceFile.read() % conf_options)
        sourceFile.close()
        targetFile.close()

config_files = ['client.conf',
                'db.conf',
                'filter.conf',
                'keysign.conf',
                'ldap.conf',
                'log.conf',
                'otut.conf',
                'pod.conf', 
                'server.conf',
                'ssl.conf',
                'tbxsosd.conf',
                'web.conf']

conf_options['confdir'] = env['CONFDIR']
env.AlwaysBuild(env.Command("ssl.conf", "ssl.conf.in", template_build))

for cf in config_files:
    env.Install(dir = env['CONFDIR'], target = cf)
