# hey emacs, this is -*- python -*-
#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
Import('env')

wwwDir = Dir(os.path.join(env['WWWDIR'], 'xmlrpc'))
confDir = Dir(os.path.join(env['CONFDIR']))

apacheConf = env.Substfile('tbxsos-xmlrpc.site.conf.in',
                           SUBST_DICT = {'\$WWWDIR': str(wwwDir)})
apacheDir = Dir(os.path.join('/etc', 'apache2', 'conf.d'))


env.Install(source = File('tbxsos-xmlrpc.py'), 
            target = wwwDir)
env.Install(source = apacheConf,
            target = apacheDir)
env.InstallAs(source = File(os.path.join('config-stock', "kpsapi.ini.stock")),
              target = File(os.path.join(str(confDir), "tbxsos-xmlrpc.ini")))

env.Alias('install', apacheDir)
