#
# Copyright (C) 2006-2012 Opersys inc.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License, not any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('env')

# Files to be compiled.
libcomm_FILES = ['gen_comm.c',
                 'sock_comm.c',
                 'ssl_comm.c',
                 'file_comm.c',
                 'poll_comm.c',
                 'misc_comm.c']

# Build the library.
cpp_path = env['CPPPATH'] + ['#libutils', '#common']
lib_comm = env.StaticLibrary('tbxsosd_comm',
                             libcomm_FILES,
                             CPPPATH = cpp_path)

Return('lib_comm')
