# Hey, Emacs! This is a -*- Python -*- file!
#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Import('env dbdir')

db_files = ['db/01-create_db.sqlpy',
            'db/10-create_event_db.sqlpy',
            'db/10-create_keys_db.sqlpy',
            'db/10-create_login_db.sqlpy',
            'db/10-create_otut_db.sqlpy',
            'db/10-create_profiles_db.sqlpy']

api_files = ['api/10-create_event_proc.sqlpy',
             'api/20-create_grants.sqlpy',
             'api/02-create_groups.sqlpy',
             'api/10-create_keys_proc.sqlpy',
             'api/10-create_login_proc.sqlpy',
             'api/10-create_otut_proc.sqlpy',
             'api/10-create_profiles_proc.sqlpy',
             'api/01-create_users.sqlpy',
             'api/drop_groups.sqlpy',
             'api/drop_misc.sqlpy',
             'api/drop_users.sqlpy']

xmlrpc_files = ['xmlrpc/30-tbxsos_xmlrpc_db.sqlpy']

for dbf in db_files:
    env.Install(dir = dbdir, target = dbf)

for dba in api_files:
    env.Install(dir = dbdir, target = dba)

for dbx in xmlrpc_files:
    env.Install(dir = dbdir, target = dbx)
