#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
Import('env conf_options prefix bindir confdir')

pyKctlDir = os.path.join(str(env['DESTDIR']), "share", "python-support")

library_files = [
    'kctllib/__init__.py',
    'kctllib/kbin.py',
    'kctllib/kdatabase.py',
    'kctllib/kexcept.py',
    'kctllib/kiniconfig.py',
    'kctllib/kkeys.py',
    'kctllib/kparams.py',
    'kctllib/ktbxsosdconfigdaemon.py',
    'kctllib/ktbxsosdconfig.py']

command_files = [
    'kctlcmd/__init__.py',
    'kctlcmd/key_cmd.py',
    'kctlcmd/login_cmd.py',
    'kctlcmd/misc_cmd.py',
    'kctlcmd/misc.py',
    'kctlcmd/org_cmd.py',
    'kctlcmd/prof_cmd.py']
    
kctl_prog = File("#kctl/kctl")

kctlcmd_lib = env.Dir(os.path.join(pyKctlDir, "kctlcmd"))
kctllib_lib = env.Dir(os.path.join(pyKctlDir, "kctllib"))

def kconfig_py_build(target, source, env):
    kconfig_py_defines = conf_options
    for a_target, a_source in zip(target, source):
        kconfig_py = file(str(a_target), "w")
        kconfig_py_in = file(str(a_source), "r")
        kconfig_py.write(kconfig_py_in.read() % kconfig_py_defines)
        kconfig_py_in.close()
        kconfig_py.close()

env.AlwaysBuild(env.Command('kctllib/kconfig.py', 
                            'kctllib/kconfig.py.in', 
                            kconfig_py_build))

if 'install' in COMMAND_LINE_TARGETS and not env.GetOption('clean'):   
    env.Install(bindir, kctl_prog)

    for s in command_files:
        env.Install(kctllib_lib, s)
        
    for s in library_files:
        env.Install(kctlcmd_lib, s)

env.Alias('install', pyKctlDir)
