# Hey, Emacs! This is a -*- Python -*- file!
#
# Copyright (C) 2006-2012 Opersys inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
Import('env conf_options prefix bindir confdir pydir')

def template_build(target, source, env):
    for a_target, a_source in zip(target, source):
        targetFile = file(str(a_target), "w")
        sourceFile = file(str(a_source), "r")
        targetFile.write(sourceFile.read() % conf_options)
        sourceFile.close()
        targetFile.close()

# Passed to the kctl.sh template.
conf_options['pydir'] = pydir

library_files = env.Glob("kctllib/*.py")
command_files = env.Glob("kctlcmd/*.py")
    
env.AlwaysBuild(env.Command('kctl', 'kctl.sh.in', 
                            [template_build, Chmod("$TARGET", 0755)]))

kctl_sh = File("kctl")
kctl_prog = File("kctl.py")
kctlcmd_lib = env.Dir(os.path.join(str(pydir), "kctlcmd"))
kctllib_lib = env.Dir(os.path.join(str(pydir), "kctllib"))

if 'install' in COMMAND_LINE_TARGETS and not env.GetOption('clean'):
    env.Install(pydir, kctl_prog)
    env.Install(bindir, kctl_sh)

    for s in command_files:
        env.Install(kctlcmd_lib, s)
        
    for s in library_files:
        env.Install(kctllib_lib, s)
