#
# Copyright (C) 2006-2012 Opersys inc.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License, not any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('env')

libfilters_FILES = ['filter_spam.c',
                    'filter_virus.c',
                    'filter_from.c',
                    'filter_forward.c',
                    'filters.c']

# Build the library.
cpp_path = env['CPPPATH'] + ['#libutils', '#common', '#libcomm', '#libdb']
libfilters = env.StaticLibrary('tbxsosd_filters',
                               libfilters_FILES,
                               CPPPATH = cpp_path)

Return('libfilters')
